# Inserts a blank line between shell prompts
add_newline = false

# Replace the '❯' symbol in the prompt with '➜'
[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✖](bold red) "

[line_break]
disabled = true
